# Documentation: https://docs.readthedocs.io/en/stable/config-file/v2.html

# Configuration file version:
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  builder: html

# Additional documentation formats (pdf, etc.)
formats: all

# Python and requirements required to build your docs
python:
  version: 3.6
  install:
    - method: pip
      path: .
      requirements: requirements.txt        # Required for the entire package
      extra_requirements:
        - docs
